image:
  repository: registry.example.test/pe-k8s-runtime
  tag: "2025.9.0"
  pullPolicy: IfNotPresent

nameOverride: ""
instanceOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

affinity: {}

tolerations: []

probes:
  startup:
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 60
  readiness:
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 3

network:
  technicalHostname: ""
  compilerHostname: ""
  additionalDnsAltNames: []
  podLoopbackAliases:
    - puppet
  hostAliases: []

peConfig:
  consoleAdminPassword: "dummyPassword1!"
  certname: ""
  puppetMasterHost: ""
  extra: ""

codeManager:
  enabled: false
  autoConfigure: true
  r10kRemote: ""
  r10kPrivateKeyPath: /r10k-secret/r10k-deploy-key
  r10kPrivateKeySecretName: ""
  r10kPrivateKeySecretKey: r10k-deploy-key
  r10kKnownHosts: []
  r10kRemoteTimeout: 60

license:
  secretName: ""

storage:
  etc:
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClassName: ""
  opt:
    accessModes:
      - ReadWriteOnce
    size: 50Gi
    storageClassName: ""
  runtime:
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClassName: ""

installer:
  forceReinstall: false
  resources: {}

postgresql:
  resources: {}

puppetdb:
  resources: {}

puppetserver:
  resources: {}

compilers:
  enabled: false
  replicaCount: 0
  dnsAltNames: []
  pcpBrokerHost: ""
  classifierWaitTimeoutSeconds: 900
  puppetdbSyncIntervalMinutes: 5
  puppetdbMaxSyncAgeSeconds: 900
  certWaitTimeoutSeconds: 900
  signerWaitTimeoutSeconds: 900
  resources:
    classifier: {}
    install: {}
    bootstrap: {}
    signer: {}
    postgresql: {}
    puppetserver: {}
    puppetdb: {}
  storage:
    etc:
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      storageClassName: ""
    opt:
      accessModes:
        - ReadWriteOnce
      size: 20Gi
      storageClassName: ""
    runtime:
      accessModes:
        - ReadWriteOnce
      size: 2Gi
      storageClassName: ""

peServices:
  replicaCount: 1
  resources:
    nginx: {}
    consoleServices: {}
    orchestrationServices: {}
    boltServer: {}
    aceServer: {}
    hostActionCollector: {}

services:
  pe:
    type: ClusterIP
    loadBalancerIP: ""
  compilers:
    type: ClusterIP
    port: 8140
    pcpPort: 8142
    loadBalancerIP: ""
  consoleServices:
    type: ClusterIP
    port: 4433
  orchestration:
    type: ClusterIP
    pcpPort: 8142
    servicePort: 8143
    codeManagerPort: 8170
  hostActionCollector:
    type: ClusterIP
    port: 8147
  boltServer:
    type: ClusterIP
    port: 62658
  aceServer:
    type: ClusterIP
    port: 44633

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: puppet.example.test
  tls:
    enabled: true
    secretName: puppet-example-test-tls
