image:
  repository: registry.example.test/pe-k8s-agent
  tag: "0.1.1"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

affinity: {}

tolerations: []

agent:
  replicaCount: 1
  server: pe
  caServer: pe
  serverList: ""
  environment: production
  certname: ""
  certnameSuffix: ".test.puppet"
  packageRepoServer: ""
  packageRepoUrl: ""
  packageRepoSslVerify: false
  runinterval: 30m
  waitforcert: 60
  splay: true
  pxpEnabled: true
  pxpLoglevel: info
  resources: {}

signer:
  enabled: true
  peReleaseName: pe
  waitTimeoutSeconds: 900
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  image:
    repository: registry.example.test/pe-k8s-runtime
    tag: "2025.9.0"
    pullPolicy: IfNotPresent
  resources: {}

storage:
  etc:
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    storageClassName: ""
  cache:
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClassName: ""

probes:
  startup:
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 60
  readiness:
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    timeoutSeconds: 5
    periodSeconds: 30
    failureThreshold: 3
