# Copy to local/values-agent.yaml and edit for your environment.

image:
  repository: registry.example.test/pe-k8s-agent
  tag: "0.1.6"

agent:
  server: pe-compiler.example.test
  caServer: ""

signer:
  image:
    repository: registry.example.test/pe-k8s-runtime
    tag: "2025.9.0-k8s131"

storage:
  etc:
    storageClassName: CHANGE_ME
  cache:
    storageClassName: CHANGE_ME
