FROM python:3.12-alpine

RUN addgroup -S conductor && adduser -S -G conductor conductor

COPY conductor-image/scripts/warden.py /usr/local/bin/conductor-warden

RUN chmod 0755 /usr/local/bin/conductor-warden

USER conductor

ENTRYPOINT ["/usr/local/bin/conductor-warden"]
