{{- if .Values.certificateRecovery.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pe.fullname" . }}-cert-recover-r{{ .Release.Revision }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.certificateRecovery.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.certificateRecovery.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "pe.labels" . | nindent 8 }}
        app.kubernetes.io/component: cert-recovery
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "pe.serviceAccountName" . }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
        - name: cert-recovery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/pe-k8s-entrypoint", "recover-cert"]
          env:
            - name: PE_CONF_PATH
              value: /config/pe.conf
            - name: PE_CERT_REGEN_CERTNAME
              value: {{ include "pe.certname" . | quote }}
            - name: PE_CERT_REGEN_DNS_ALT_NAMES
              value: {{ include "pe.dnsAltNamesCsv" . | quote }}
          resources:
{{ toYaml .Values.certificateRecovery.resources | indent 12 }}
          volumeMounts:
            - name: pe-conf
              mountPath: /config
              readOnly: true
            - name: etc
              mountPath: /etc/puppetlabs
            - name: opt
              mountPath: /opt/puppetlabs
            - name: runtime
              mountPath: /var/lib/pe-k8s
            - name: logs
              mountPath: /var/log/puppetlabs
      volumes:
        - name: pe-conf
          configMap:
            name: {{ include "pe.fullname" . }}-conf
        - name: etc
          persistentVolumeClaim:
            claimName: {{ include "pe.fullname" . }}-etc
        - name: opt
          persistentVolumeClaim:
            claimName: {{ include "pe.fullname" . }}-opt
        - name: runtime
          persistentVolumeClaim:
            claimName: {{ include "pe.fullname" . }}-runtime
        - name: logs
          emptyDir: {}
{{- end }}
