{{- if .Values.certificateRegeneration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pe.fullname" . }}-cert-regen-r{{ .Release.Revision }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.certificateRegeneration.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.certificateRegeneration.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "pe.labels" . | nindent 8 }}
        app.kubernetes.io/component: cert-regeneration
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "pe.serviceAccountName" . }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      containers:
        - name: cert-regeneration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/pe-k8s-entrypoint", "regenerate-cert"]
          env:
            - name: PE_CONF_PATH
              value: /config/pe.conf
            - name: PE_CERT_REGEN_CERTNAME
              value: {{ include "pe.certname" . | quote }}
            - name: PE_CERT_REGEN_DNS_ALT_NAMES
              value: {{ include "pe.dnsAltNamesCsv" . | quote }}
            - name: PE_CERT_REGEN_MANAGE_PXP
              value: {{ ternary "true" "false" .Values.certificateRegeneration.managePxpService | quote }}
            - name: PE_CERT_REGEN_FORCE
              value: {{ ternary "true" "false" .Values.certificateRegeneration.force | quote }}
          resources:
{{ toYaml .Values.certificateRegeneration.resources | indent 12 }}
          volumeMounts:
            - name: pe-conf
              mountPath: /config
              readOnly: true
            - name: etc
              mountPath: /etc/puppetlabs
            - name: opt
              mountPath: /opt/puppetlabs
            - name: runtime
              mountPath: /var/lib/pe-k8s
            - name: logs
              mountPath: /var/log/puppetlabs
      volumes:
        - name: pe-conf
          configMap:
            name: {{ include "pe.fullname" . }}-conf
        - name: etc
          persistentVolumeClaim:
            claimName: {{ include "pe.fullname" . }}-etc
        - name: opt
          persistentVolumeClaim:
            claimName: {{ include "pe.fullname" . }}-opt
        - name: runtime
          persistentVolumeClaim:
            claimName: {{ include "pe.fullname" . }}-runtime
        - name: logs
          emptyDir: {}
{{- end }}
