{{- if and .Values.compilers.enabled (gt (int .Values.compilers.replicaCount) 0) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pe.fullname" . }}-jobs-reader
  labels:
    {{- include "pe.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pe.fullname" . }}-jobs-reader
  labels:
    {{- include "pe.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pe.fullname" . }}-jobs-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "pe.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
