{{- if eq .Values.controlPlane.ca.provider "releaseRoot" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pe.fullname" . }}-release-root-ca-secret-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pe.fullname" . }}-control-plane-ca-bootstrap
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pe.fullname" . }}-release-root-ca-secret-manager
{{- end }}
