apiVersion: v1
kind: Service
metadata:
  name: {{ include "pe.controlPlaneHeadlessServiceName" . }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pe-services
  ports:
    - name: http
      port: 80
      targetPort: nginx-http
    - name: https
      port: 443
      targetPort: nginx-https
    - name: postgresql
      port: 5432
      targetPort: postgresql
    - name: puppetdb
      port: 8081
      targetPort: puppetdb
    - name: puppetserver
      port: 8140
      targetPort: puppetserver
    - name: pcp-broker
      port: 8142
      targetPort: orch-pcp
    - name: orchestration
      port: 8143
      targetPort: orch-svc
    - name: host-action
      port: 8147
      targetPort: hac-svc
    {{- if .Values.codeManager.enabled }}
    - name: code-manager
      port: 8170
      targetPort: code-manager
    {{- end }}
    - name: console-api
      port: 4433
      targetPort: console-svc
    - name: bolt-server
      port: 62658
      targetPort: bolt-svc
    - name: ace-server
      port: 44633
      targetPort: ace-svc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pe.identity" . }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.pe.type }}
  {{- if .Values.services.pe.loadBalancerIP }}
  loadBalancerIP: {{ .Values.services.pe.loadBalancerIP }}
  {{- end }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pe-services
  ports:
    - name: http
      port: 80
      targetPort: nginx-http
    - name: https
      port: 443
      targetPort: nginx-https
    - name: postgresql
      port: 5432
      targetPort: postgresql
    - name: puppetdb
      port: 8081
      targetPort: puppetdb
    - name: puppetserver
      port: 8140
      targetPort: puppetserver
    - name: pcp-broker
      port: 8142
      targetPort: orch-pcp
    - name: orchestration
      port: 8143
      targetPort: orch-svc
    - name: host-action
      port: 8147
      targetPort: hac-svc
    {{- if .Values.codeManager.enabled }}
    - name: code-manager
      port: 8170
      targetPort: code-manager
    {{- end }}
    - name: console-api
      port: 4433
      targetPort: console-svc
    - name: bolt-server
      port: 62658
      targetPort: bolt-svc
    - name: ace-server
      port: 44633
      targetPort: ace-svc
