apiVersion: v1
kind: Service
metadata:
  name: {{ include "pe.controlPlaneHeadlessServiceName" . }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pe-services
  ports:
    - name: http
      port: 80
      targetPort: nginx-http
    - name: https
      port: 443
      targetPort: nginx-https
    - name: postgresql
      port: 5432
      targetPort: postgresql
    - name: puppetdb
      port: 8081
      targetPort: puppetdb
    - name: puppetserver
      port: 8140
      targetPort: puppetserver
    - name: pcp-broker
      port: 8142
      targetPort: {{ ternary "gw-pcp" "orch-pcp" (and .Values.conductor.enabled .Values.conductor.gateway.enabled .Values.conductor.gateway.pcp.enabled) }}
    - name: orchestration
      port: 8143
      targetPort: {{ ternary "gw-orch" "orch-svc" (and .Values.conductor.enabled .Values.conductor.gateway.enabled .Values.conductor.gateway.orchestration.enabled) }}
    - name: host-action
      port: 8147
      targetPort: hac-svc
    {{- if .Values.codeManager.enabled }}
    - name: code-manager
      port: 8170
      targetPort: code-manager
    {{- end }}
    - name: console-api
      port: 4433
      targetPort: console-svc
    - name: bolt-server
      port: 62658
      targetPort: bolt-svc
    - name: ace-server
      port: 44633
      targetPort: ace-svc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pe.identity" . }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.pe.type }}
  {{- if .Values.services.pe.loadBalancerIP }}
  loadBalancerIP: {{ .Values.services.pe.loadBalancerIP }}
  {{- end }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pe-services
  ports:
    - name: http
      port: 80
      targetPort: nginx-http
    - name: https
      port: 443
      targetPort: nginx-https
    - name: postgresql
      port: 5432
      targetPort: postgresql
    - name: puppetdb
      port: 8081
      targetPort: puppetdb
    - name: puppetserver
      port: 8140
      targetPort: puppetserver
    - name: pcp-broker
      port: 8142
      targetPort: {{ ternary "gw-pcp" "orch-pcp" (and .Values.conductor.enabled .Values.conductor.gateway.enabled .Values.conductor.gateway.pcp.enabled) }}
    - name: orchestration
      port: 8143
      targetPort: {{ ternary "gw-orch" "orch-svc" (and .Values.conductor.enabled .Values.conductor.gateway.enabled .Values.conductor.gateway.orchestration.enabled) }}
    - name: host-action
      port: 8147
      targetPort: hac-svc
    {{- if .Values.codeManager.enabled }}
    - name: code-manager
      port: 8170
      targetPort: code-manager
    {{- end }}
    - name: console-api
      port: 4433
      targetPort: console-svc
    - name: bolt-server
      port: 62658
      targetPort: bolt-svc
    - name: ace-server
      port: 44633
      targetPort: ace-svc
{{- if and .Values.compilers.enabled (gt (int .Values.compilers.replicaCount) 0) (gt (int .Values.controlPlane.replicaCount) 1) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pe.controlPlaneFileSyncServiceName" . }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pe-services
    pe-k8s.puppet.com/filesync-active: "true"
  ports:
    - name: puppetserver
      port: 8140
      targetPort: puppetserver
{{- end }}
{{- if eq (include "pe.consoleStickyEnabled" .) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pe.consoleServiceName" . }}
  labels:
    {{- include "pe.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pe-services
    pe-k8s.puppet.com/console-active: "true"
  ports:
    - name: http
      port: 80
      targetPort: nginx-http
{{- end }}
