apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppet-agent.fullname" . }}
  labels:
    {{- include "puppet-agent.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "puppet-agent.selectorLabels" . | nindent 4 }}
