{{- if not .Values.hub.auth.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "conductor.hubAuthSecretName" . }}
  labels:
{{ include "conductor.labels" . | indent 4 }}
type: Opaque
stringData:
  {{ .Values.hub.auth.usernameKey }}: {{ .Values.hub.auth.username | quote }}
  {{ .Values.hub.auth.passwordKey }}: {{ .Values.hub.auth.password | quote }}
{{- end }}
