apiVersion: v1
kind: Service
metadata:
  name: {{ include "conductor.hubHeadlessServiceName" . }}
  labels:
{{ include "conductor.labels" . | indent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "conductor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub
  ports:
    - name: amqp
      port: {{ .Values.hub.service.amqpPort }}
      targetPort: amqp
    - name: management
      port: {{ .Values.hub.service.managementPort }}
      targetPort: management
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "conductor.hubServiceName" . }}
  labels:
{{ include "conductor.labels" . | indent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  {{- if and (eq .Values.hub.service.type "LoadBalancer") .Values.hub.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.hub.service.loadBalancerIP }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "conductor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: hub
  ports:
    - name: amqp
      port: {{ .Values.hub.service.amqpPort }}
      targetPort: amqp
    - name: management
      port: {{ .Values.hub.service.managementPort }}
      targetPort: management
