{{- if and (eq (include "conductor.wardenEnabled" .) "true") .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "conductor.serviceAccountName" . }}
  labels:
{{ include "conductor.labels" . | indent 4 }}
{{- end }}
